export type UserProps = {
  nome: string;
  nomeSocial?: string;
  nomeMae?: string;
  nomePai?: string;
  estadoCivil: string;
  idade: number;
  dataNascimento: string;
  sexo: string;
  estado: string;
  cidade: string;
  bairro: string;
  cep: string;
  logradouro: string;
  tipoLogradouro: string | null;
  complemento: string | null;
  numero: number;
  telResidencial: string | null;
  telCelular: string | null;
  telOutro: string | null;
  email: string;
  cpf: string;
  rg: string;
  rgdg: string | null;
  orgaoEmissor: string;
  ufIdentidade: string;
  tipoIdentidade: string;
  identidade: string;
  contribuinte: string;
  NumeroSPPrev: string | null;
  postoPolicial: string;
  matricula: any;
};
