enum Forms {
  INCLUSAO_CONJUGE = 1,
  INCLUSAO_COMPANHEIRO = 2,
  INCLUSAO_FILHOS_E_ENTEADOS = 3,
  INCLUSAO_GENITORES = 4,
  INCLUSAO_MENOR_SOB_GUARDA = 5,
  BENEFICIARIO_INVALIDEZ = 6,
  EXCLUSAO_CONJUGE_ENTEADO = 7,
  EXCLUSAO_COMPANHEIRA_ENTEADO = 8,
  INCLUSAO_ATUALIZAÇAO_DADOS_PENSIONISTA = 9,
  REQUERIMENTO_SOLICITACAO_GERAL = 10,
  REQUERIMENTO_REINCLUSAO_ADMINISTRATIVA = 11,
  FORMULARIO_DECLARACAO_SAUDE = 12,
  ATUALIZACAO_DE_DADOS = 13,
}

export default Forms
